global X_var=Base
address="172.16.58.34"
port=3000
X_error=False
socket_open(address,port)
socket_send_line("X2()")
ret=socket_read_line(timeout=10)
#popup(ret,title="ret",blocking=True)
if (ret != "OK"):
  X_error=True
  socket_close()
else:
  f=socket_read_ascii_float(6)
  while (f[0]!=6):
    sleep(0.3)
    f=socket_read_ascii_float(6)
  end
  socket_close()
  X_var[0]=f[1]
  X_var[1]=f[2]
  X_var[2]=f[3]
  X_var[3]=f[4]
  X_var[4]=f[5]
  X_var[5]=f[6]
end